import {
  ArrowRightIcon,
  CalendarIcon,
  CaseSensitiveIcon,
  CheckSquareIcon,
  CircleQuestionMarkIcon,
  CircleUserRoundIcon,
  ClockIcon,
  HashIcon,
  LinkIcon,
  ListIcon,
  LoaderIcon,
  type LucideIcon,
  MailIcon,
  MapPinIcon,
  PaperclipIcon,
  PhoneIcon,
  SigmaIcon,
  TagIcon,
  TextAlignStartIcon,
  UsersIcon,
} from "lucide-react";

export const properties = [
  "checkbox",
  "created_by",
  "created_time",
  "date",
  "email",
  "files",
  "formula",
  "last_edited_by",
  "last_edited_time",
  "multi_select",
  "number",
  "unique_id",
  "people",
  "phone_number",
  "place",
  "relation",
  "rich_text",
  "rollup",
  "select",
  "status",
  "title",
  "url",
] as const;
export type PropertyType = (typeof properties)[number];
export const propertiesIcons: Record<PropertyType, LucideIcon> = {
  checkbox: CheckSquareIcon,
  created_by: CircleUserRoundIcon,
  created_time: ClockIcon,
  date: CalendarIcon,
  email: MailIcon,
  files: PaperclipIcon,
  formula: SigmaIcon,
  last_edited_by: CircleUserRoundIcon,
  last_edited_time: ClockIcon,
  multi_select: ListIcon,
  number: HashIcon,
  unique_id: HashIcon,
  people: UsersIcon,
  phone_number: PhoneIcon,
  place: MapPinIcon,
  relation: ArrowRightIcon,
  rich_text: TextAlignStartIcon,
  rollup: SigmaIcon,
  select: TagIcon,
  status: LoaderIcon,
  title: CaseSensitiveIcon,
  url: LinkIcon,
} as const;

export const PropertyIcon = ({
  type,
  ...rest
}: { type: PropertyType } & React.ComponentProps<LucideIcon>) => {
  const IconComponent = propertiesIcons[type] || CircleQuestionMarkIcon;
  return <IconComponent {...rest} />;
};
